import type { Metadata } from "next";
import { Cormorant_Infant, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const cormorantInfant = Cormorant_Infant({
  subsets: ["latin", "cyrillic"], // для русского языка
  weight: ["300", "400", "500", "600", "700"], // доступные начертания
  variable: "--font-cormorant", // для CSS переменной
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorantInfant.className} antialiased min-h-screen bg-gradient-to-br from-[#080E1C] to-[#183060] text-white`}
      >
        {children}
      </body>
    </html>
  );
}
